defmodule Realworld.Repo.Migrations.RemoveIdFromTokens do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # alter table(:token) do
    # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
    # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
    # remove :id
    # end
    # 
  end

  def down do
    # alter table(:token) do
    # This is the `down` migration of the statement:
    #
    #     remove :id
    #
    # 
    # add :id, :uuid, null: false, primary_key: true
    # end
    # 
  end
end
