defmodule Realworld.Repo.Migrations.Reactions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:reaction, primary_key: false) do
      add :comment_id,
          references(:comment,
            column: :id,
            name: "reaction_comment_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ),
          null: false

      add :user_id,
          references(:user,
            column: :id,
            name: "reaction_user_id_fkey",
            type: :uuid,
            on_delete: :delete_all
          ),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :created_at, :utc_datetime_usec, null: false
      add :type, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:reaction, [:user_id, :comment_id],
             name: "reaction_unique_user_comment_reaction_index"
           )
  end

  def down do
    drop_if_exists unique_index(:reaction, [:user_id, :comment_id],
                     name: "reaction_unique_user_comment_reaction_index"
                   )

    drop constraint(:reaction, "reaction_user_id_fkey")

    drop constraint(:reaction, "reaction_comment_id_fkey")

    drop table(:reaction)
  end
end