defmodule Realworld.Repo.Migrations.FollowTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:follow, primary_key: false) do
      add :target_id, references(:user, column: :id, name: "follow_target_id_fkey", type: :uuid),
        primary_key: true,
        null: false

      add :user_id, references(:user, column: :id, name: "follow_user_id_fkey", type: :uuid),
        primary_key: true,
        null: false

      add :created_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:follow, [:target_id, :user_id], name: "follow_unique_follow_index")
  end

  def down do
    drop_if_exists unique_index(:follow, [:target_id, :user_id],
                     name: "follow_unique_follow_index"
                   )

    drop constraint(:follow, "follow_user_id_fkey")

    drop constraint(:follow, "follow_target_id_fkey")

    drop table(:follow)
  end
end
